// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 구조체 역할
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// REDIS
// 1,2 = 필드 순서 및 식별자 유니크
type SaveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveSessionRequest) Reset() {
	*x = SaveSessionRequest{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSessionRequest) ProtoMessage() {}

func (x *SaveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSessionRequest.ProtoReflect.Descriptor instead.
func (*SaveSessionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *SaveSessionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SaveSessionRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SaveSessionRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SaveSessionWithTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          string                 `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int64                  `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"` // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveSessionWithTargetRequest) Reset() {
	*x = SaveSessionWithTargetRequest{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSessionWithTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSessionWithTargetRequest) ProtoMessage() {}

func (x *SaveSessionWithTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSessionWithTargetRequest.ProtoReflect.Descriptor instead.
func (*SaveSessionWithTargetRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *SaveSessionWithTargetRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SaveSessionWithTargetRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *SaveSessionWithTargetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SaveSessionWithTargetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SaveSessionWithTargetRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type GetSessionWithTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          string                 `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionWithTargetRequest) Reset() {
	*x = GetSessionWithTargetRequest{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionWithTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionWithTargetRequest) ProtoMessage() {}

func (x *GetSessionWithTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionWithTargetRequest.ProtoReflect.Descriptor instead.
func (*GetSessionWithTargetRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionWithTargetRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GetSessionWithTargetRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *GetSessionWithTargetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GenericResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenericResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendKafkaMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brokers       []string               `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendKafkaMessageRequest) Reset() {
	*x = SendKafkaMessageRequest{}
	mi := &file_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendKafkaMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKafkaMessageRequest) ProtoMessage() {}

func (x *SendKafkaMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKafkaMessageRequest.ProtoReflect.Descriptor instead.
func (*SendKafkaMessageRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *SendKafkaMessageRequest) GetBrokers() []string {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *SendKafkaMessageRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SendKafkaMessageRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SendKafkaMessageRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SendFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brokers       []string               `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"` // ["localhost:9092","kafka1:9093"]
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	InputPath     string                 `protobuf:"bytes,3,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	OutputPath    string                 `protobuf:"bytes,4,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileRequest) Reset() {
	*x = SendFileRequest{}
	mi := &file_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileRequest) ProtoMessage() {}

func (x *SendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileRequest.ProtoReflect.Descriptor instead.
func (*SendFileRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *SendFileRequest) GetBrokers() []string {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *SendFileRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SendFileRequest) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *SendFileRequest) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

type SendFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LinesSent     int32                  `protobuf:"varint,3,opt,name=lines_sent,json=linesSent,proto3" json:"lines_sent,omitempty"` // 송신된 라인 수
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileResponse) Reset() {
	*x = SendFileResponse{}
	mi := &file_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileResponse) ProtoMessage() {}

func (x *SendFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileResponse.ProtoReflect.Descriptor instead.
func (*SendFileResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *SendFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendFileResponse) GetLinesSent() int32 {
	if x != nil {
		return x.LinesSent
	}
	return 0
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\agateway\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"N\n" +
	"\x12SaveSessionRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\"%\n" +
	"\x11GetSessionRequest\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"|\n" +
	"\x1cSaveSessionWithTargetRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\tR\x04port\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x05 \x01(\x03R\x03ttl\"S\n" +
	"\x1bGetSessionWithTargetRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\tR\x04port\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"E\n" +
	"\x0fGenericResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"q\n" +
	"\x17SendKafkaMessageRequest\x12\x18\n" +
	"\abrokers\x18\x01 \x03(\tR\abrokers\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\x81\x01\n" +
	"\x0fSendFileRequest\x12\x18\n" +
	"\abrokers\x18\x01 \x03(\tR\abrokers\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1d\n" +
	"\n" +
	"input_path\x18\x03 \x01(\tR\tinputPath\x12\x1f\n" +
	"\voutput_path\x18\x04 \x01(\tR\n" +
	"outputPath\"e\n" +
	"\x10SendFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"lines_sent\x18\x03 \x01(\x05R\tlinesSent2\x9f\x04\n" +
	"\x0eGatewayService\x129\n" +
	"\bSayHello\x12\x15.gateway.HelloRequest\x1a\x16.gateway.HelloResponse\x12D\n" +
	"\vSaveSession\x12\x1b.gateway.SaveSessionRequest\x1a\x18.gateway.GenericResponse\x12B\n" +
	"\n" +
	"GetSession\x12\x1a.gateway.GetSessionRequest\x1a\x18.gateway.GenericResponse\x12X\n" +
	"\x15SaveSessionWithTarget\x12%.gateway.SaveSessionWithTargetRequest\x1a\x18.gateway.GenericResponse\x12V\n" +
	"\x14GetSessionWithTarget\x12$.gateway.GetSessionWithTargetRequest\x1a\x18.gateway.GenericResponse\x12N\n" +
	"\x10SendKafkaMessage\x12 .gateway.SendKafkaMessageRequest\x1a\x18.gateway.GenericResponse\x12F\n" +
	"\x0fSendFileToKafka\x12\x18.gateway.SendFileRequest\x1a\x19.gateway.SendFileResponseB3\n" +
	"\x17com.servicegateway.grpcB\fGatewayProtoP\x01Z\b./;protob\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gateway_proto_goTypes = []any{
	(*HelloRequest)(nil),                 // 0: gateway.HelloRequest
	(*HelloResponse)(nil),                // 1: gateway.HelloResponse
	(*SaveSessionRequest)(nil),           // 2: gateway.SaveSessionRequest
	(*GetSessionRequest)(nil),            // 3: gateway.GetSessionRequest
	(*SaveSessionWithTargetRequest)(nil), // 4: gateway.SaveSessionWithTargetRequest
	(*GetSessionWithTargetRequest)(nil),  // 5: gateway.GetSessionWithTargetRequest
	(*GenericResponse)(nil),              // 6: gateway.GenericResponse
	(*SendKafkaMessageRequest)(nil),      // 7: gateway.SendKafkaMessageRequest
	(*SendFileRequest)(nil),              // 8: gateway.SendFileRequest
	(*SendFileResponse)(nil),             // 9: gateway.SendFileResponse
}
var file_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.GatewayService.SayHello:input_type -> gateway.HelloRequest
	2, // 1: gateway.GatewayService.SaveSession:input_type -> gateway.SaveSessionRequest
	3, // 2: gateway.GatewayService.GetSession:input_type -> gateway.GetSessionRequest
	4, // 3: gateway.GatewayService.SaveSessionWithTarget:input_type -> gateway.SaveSessionWithTargetRequest
	5, // 4: gateway.GatewayService.GetSessionWithTarget:input_type -> gateway.GetSessionWithTargetRequest
	7, // 5: gateway.GatewayService.SendKafkaMessage:input_type -> gateway.SendKafkaMessageRequest
	8, // 6: gateway.GatewayService.SendFileToKafka:input_type -> gateway.SendFileRequest
	1, // 7: gateway.GatewayService.SayHello:output_type -> gateway.HelloResponse
	6, // 8: gateway.GatewayService.SaveSession:output_type -> gateway.GenericResponse
	6, // 9: gateway.GatewayService.GetSession:output_type -> gateway.GenericResponse
	6, // 10: gateway.GatewayService.SaveSessionWithTarget:output_type -> gateway.GenericResponse
	6, // 11: gateway.GatewayService.GetSessionWithTarget:output_type -> gateway.GenericResponse
	6, // 12: gateway.GatewayService.SendKafkaMessage:output_type -> gateway.GenericResponse
	9, // 13: gateway.GatewayService.SendFileToKafka:output_type -> gateway.SendFileResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
