// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/service-gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 구조체 역할
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_proto_service_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_proto_service_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// REDIS
// 1,2 = 필드 순서 및 식별자 유니크
type SetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionRequest) Reset() {
	*x = SetSessionRequest{}
	mi := &file_proto_service_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionRequest) ProtoMessage() {}

func (x *SetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionRequest.ProtoReflect.Descriptor instead.
func (*SetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *SetSessionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetSessionRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetSessionRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// REDIS
// 1,2 = 필드 순서 및 식별자 유니크
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_service_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSessionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateSessionRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateSessionRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_proto_service_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SetSessionWithTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int64                  `protobuf:"varint,6,opt,name=ttl,proto3" json:"ttl,omitempty"` // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionWithTargetRequest) Reset() {
	*x = SetSessionWithTargetRequest{}
	mi := &file_proto_service_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionWithTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionWithTargetRequest) ProtoMessage() {}

func (x *SetSessionWithTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionWithTargetRequest.ProtoReflect.Descriptor instead.
func (*SetSessionWithTargetRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *SetSessionWithTargetRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SetSessionWithTargetRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetSessionWithTargetRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SetSessionWithTargetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetSessionWithTargetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetSessionWithTargetRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type GetSessionWithTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionWithTargetRequest) Reset() {
	*x = GetSessionWithTargetRequest{}
	mi := &file_proto_service_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionWithTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionWithTargetRequest) ProtoMessage() {}

func (x *GetSessionWithTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionWithTargetRequest.ProtoReflect.Descriptor instead.
func (*GetSessionWithTargetRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionWithTargetRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetSessionWithTargetRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetSessionWithTargetRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetSessionWithTargetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_proto_service_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *GenericResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenericResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_service_gateway_proto protoreflect.FileDescriptor

const file_proto_service_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/service-gateway.proto\x12\x0eservie.gateway\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"M\n" +
	"\x11SetSessionRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\"P\n" +
	"\x14CreateSessionRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\"%\n" +
	"\x11GetSessionRequest\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"\xa3\x01\n" +
	"\x1bSetSessionWithTargetRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\x03R\x03ttl\"{\n" +
	"\x1bGetSessionWithTargetRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\"E\n" +
	"\x0fGenericResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2W\n" +
	"\fHelloService\x12G\n" +
	"\bSayHello\x12\x1c.servie.gateway.HelloRequest\x1a\x1d.servie.gateway.HelloResponse2\xd8\x03\n" +
	"\x0eSessionService\x12P\n" +
	"\n" +
	"SetSession\x12!.servie.gateway.SetSessionRequest\x1a\x1f.servie.gateway.GenericResponse\x12V\n" +
	"\rCreateSession\x12$.servie.gateway.CreateSessionRequest\x1a\x1f.servie.gateway.GenericResponse\x12P\n" +
	"\n" +
	"GetSession\x12!.servie.gateway.GetSessionRequest\x1a\x1f.servie.gateway.GenericResponse\x12d\n" +
	"\x14SetSessionWithTarget\x12+.servie.gateway.SetSessionWithTargetRequest\x1a\x1f.servie.gateway.GenericResponse\x12d\n" +
	"\x14GetSessionWithTarget\x12+.servie.gateway.GetSessionWithTargetRequest\x1a\x1f.servie.gateway.GenericResponseB:\n" +
	"\x18com.service.gateway.grpcB\x12SeviceGatewayProtoP\x01Z\b./;protob\x06proto3"

var (
	file_proto_service_gateway_proto_rawDescOnce sync.Once
	file_proto_service_gateway_proto_rawDescData []byte
)

func file_proto_service_gateway_proto_rawDescGZIP() []byte {
	file_proto_service_gateway_proto_rawDescOnce.Do(func() {
		file_proto_service_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_gateway_proto_rawDesc), len(file_proto_service_gateway_proto_rawDesc)))
	})
	return file_proto_service_gateway_proto_rawDescData
}

var file_proto_service_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_service_gateway_proto_goTypes = []any{
	(*HelloRequest)(nil),                // 0: servie.gateway.HelloRequest
	(*HelloResponse)(nil),               // 1: servie.gateway.HelloResponse
	(*SetSessionRequest)(nil),           // 2: servie.gateway.SetSessionRequest
	(*CreateSessionRequest)(nil),        // 3: servie.gateway.CreateSessionRequest
	(*GetSessionRequest)(nil),           // 4: servie.gateway.GetSessionRequest
	(*SetSessionWithTargetRequest)(nil), // 5: servie.gateway.SetSessionWithTargetRequest
	(*GetSessionWithTargetRequest)(nil), // 6: servie.gateway.GetSessionWithTargetRequest
	(*GenericResponse)(nil),             // 7: servie.gateway.GenericResponse
}
var file_proto_service_gateway_proto_depIdxs = []int32{
	0, // 0: servie.gateway.HelloService.SayHello:input_type -> servie.gateway.HelloRequest
	2, // 1: servie.gateway.SessionService.SetSession:input_type -> servie.gateway.SetSessionRequest
	3, // 2: servie.gateway.SessionService.CreateSession:input_type -> servie.gateway.CreateSessionRequest
	4, // 3: servie.gateway.SessionService.GetSession:input_type -> servie.gateway.GetSessionRequest
	5, // 4: servie.gateway.SessionService.SetSessionWithTarget:input_type -> servie.gateway.SetSessionWithTargetRequest
	6, // 5: servie.gateway.SessionService.GetSessionWithTarget:input_type -> servie.gateway.GetSessionWithTargetRequest
	1, // 6: servie.gateway.HelloService.SayHello:output_type -> servie.gateway.HelloResponse
	7, // 7: servie.gateway.SessionService.SetSession:output_type -> servie.gateway.GenericResponse
	7, // 8: servie.gateway.SessionService.CreateSession:output_type -> servie.gateway.GenericResponse
	7, // 9: servie.gateway.SessionService.GetSession:output_type -> servie.gateway.GenericResponse
	7, // 10: servie.gateway.SessionService.SetSessionWithTarget:output_type -> servie.gateway.GenericResponse
	7, // 11: servie.gateway.SessionService.GetSessionWithTarget:output_type -> servie.gateway.GenericResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_service_gateway_proto_init() }
func file_proto_service_gateway_proto_init() {
	if File_proto_service_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_gateway_proto_rawDesc), len(file_proto_service_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_service_gateway_proto_goTypes,
		DependencyIndexes: file_proto_service_gateway_proto_depIdxs,
		MessageInfos:      file_proto_service_gateway_proto_msgTypes,
	}.Build()
	File_proto_service_gateway_proto = out.File
	file_proto_service_gateway_proto_goTypes = nil
	file_proto_service_gateway_proto_depIdxs = nil
}
