application:
  name: "service-gateway"
  group_code: "006"
  log:
    topic: "topic1"
    inbound:
      request: "log.source.in"
      response: "log.source.out"
    outbound:
      request: "log.target.in"
      response: "log.target.out"

kafka:
  enabled: true
  brokers: ["localhost:9092"]
  client_id: "service-gateway"
  acks: "all"                 # none|leader|all
  compression: "snappy"       # none|gzip|snappy|lz4|zstd
  timeout_ms: 5000            # 개별 write 타임아웃
  batch_bytes: 1048576        # 1MiB
  batch_timeout_ms: 10
  sasl:
    enabled: false
    mechanism: "SCRAM-SHA-256"
    username: ""
    password: ""
  tls:
    enabled: false
    insecure_skip_verify: false

server:
  addr: ":8092"
  read_timeout_ms: 5000
  write_timeout_ms: 5000
  idle_timeout_ms: 60000

db:
  enabled: true   
  driver: "mysql"        # "mysql" (MariaDB 드라이버)
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "1234"
  name: "test"      # schema/database name


hosts:
  session-service: localhost:8090
  "003": http://localhost:8090
  order-service: localhost:8092
  mock-host: localhost:8093

routes:
  - name: save-user 
    match:
      path_prefix: /save/user
      methods: [POST, PUT]
    backend:
      scheme: http
      host: "localhost:8090"
      path_rewrite: "/v1/session/save"  # /echo/* -> /anything
    options:
      require_session: true
      generate_if_missing: true


# === dynamic session endpoints ===
  - name: find-user-info
    match:
      path_pattern: /get/user/{field}
      methods: [GET]
    backend:
      scheme: http
      host: "localhost:8090"
      path_rewrite: "/v1/session/find/field"
      method: "POST"
    options:
      require_session: false
      generate_if_missing: true

  - name: update
    match:
      path_prefix: /api/update
      methods: [GET]
    backend:
      scheme: http
      host: "localhost:8090"
      path_rewrite: "/v1/update"
    options:
      require_session: true
      generate_if_missing: false

  - name: refresh
    match:
      path_prefix: /api/refresh
      methods: [POST, PUT]
    backend:
      scheme: http
      host: "localhost:8090"
      path_rewrite: "/v1/refresh"
    options:
      require_session: true
      generate_if_missing: false

tracing:
  enabled: true
  otlp:
    endpoint: "127.0.0.1:4317"
    insecure: true

middleware:
  circuitbreaker:
    enabled: true
    failureThreshold: 5
    openTimeoutMs: 10000
    halfOpenTimeoutMs: 5000
  ratelimit:
    enabled: true
    rate: 100   # requests per second
    burst: 10


